cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]

c_compiler:          # [osx]
  - clang_bootstrap  # [osx]

c_compiler_version:     # [osx]
  - "*"                 # [osx]

cxx_compiler_version:   # [osx]
  - "*"                 # [osx]
