{% set version = "6.0.1" %}
{% set sha256 = "7c243f1485bddfdfedada3cd402ff4792ea82362ff91fbdac2dae67c6026b667" %}

{% set build_number = 1001 %}

package:
  name: clangdev
  version: {{ version }}

source:
  fn: cfe-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/cfe-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # This (system) libxml2 may not be available on user systems.
    - disable-libxml2-detection.patch  # [linux]

build:
  number: {{ build_number }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake-binary >=3.4.3
    # Needed to unpack the source tarball
    - m2w64-xz  # [win]
    # "compiling .pyc files" fails without this
    - python >3
  host:
    - llvmdev =={{ version }}
    - libxml2
  run:
    - llvmdev =={{ version }}
    - libxml2

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake-binary >=3.4.3
  files:
    - mytest.c
  commands:
    - $PREFIX/bin/clang --version  # [unix]
    - $PREFIX/bin/clang++ --version  # [unix]
    - $PREFIX/bin/clang-check --version  # [unix]

    - $PREFIX/bin/clang -v -c mytest.c      # [unix]
    - "%LIBRARY_BIN%/clang -v -c mytest.c"  # [win]

    - if not exist %LIBRARY_INC%\\clang\\Lex\\Lexer.h exit 1  # [win]
    - test -f $PREFIX/include/clang/Lex/Lexer.h      # [unix]
    - test -f $PREFIX/lib/libclangBasic.a            # [unix]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for Clang

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - jakirkham
    - mattwala
    - SylvainCorlay
