# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

version: 2

jobs:
  build_osx_clang_variantcling_v0.6:
    working_directory: ~/test
    macos:
      xcode: "9.0"
    environment:
      - CONFIG: "osx_clang_variantcling_v0.6"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: |
            export CI=circle
            ./.circleci/run_osx_build.sh
  build_osx_clang_variantdefault:
    working_directory: ~/test
    macos:
      xcode: "9.0"
    environment:
      - CONFIG: "osx_clang_variantdefault"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: |
            export CI=circle
            ./.circleci/run_osx_build.sh
  build_osx_clang_variantroot_v6.18.02:
    working_directory: ~/test
    macos:
      xcode: "9.0"
    environment:
      - CONFIG: "osx_clang_variantroot_v6.18.02"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: |
            export CI=circle
            ./.circleci/run_osx_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_osx_clang_variantcling_v0.6
      - build_osx_clang_variantdefault
      - build_osx_clang_variantroot_v6.18.02
